# Nombre del Workflow
name: Deploy to Hostmanía

# Disparador: se ejecuta cada vez que haces 'push' a la rama 'main'
on:
  push:
    branches: [ main ]

# Tareas a ejecutar
jobs:
  deploy:
    # Usa un servidor virtual de Linux para ejecutar los pasos
    runs-on: ubuntu-latest

    steps:
    # 1. Paso de conexión y ejecución de comandos en tu servidor
    - name: Deploy to Server
      # Usa una 'Action' popular de la comunidad para facilitar la conexión SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        timeout: 60s
        known_hosts: |
          [77.37.88.109]:65002 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDT29lzcgTJIyfLKiOGJfmVKjwz8z9Zoac6qBRZysbIuuceZYz6ZVchIrpbP4igvdn8pBk10IlB5I3ZpQe7hiH6hzHsYvuOXN/QJ8dXfxVBawq1KMWwvBx7U6cJWy4itqd3DFPy+UXgO2XJXT1P9IQT2sGhYP4jSom4CSvfKVQ17RTQYwvt+9SkSTeZzTNdRo0SXu1GKUZZS69oSXjaAoj+ctT2sOaZUr/0+R1F9rGGJ4XoVi1/gLKFiRXU63Rt3EljHbeTo/ZjmDFFPzTPvYLWT+E8eNIGHS/9TC8X2RT45LT8P0qnbe5854t5fFbTE/xvvdD9EwkKz7NLUS9cyk2MuwOdaQYOG7wVx2XS7lXCXt7F3+4GVNGr/oqkEYUdS4Qg2h7XxE9yceI7/KCzQVfeAXngVzHGxoONQZEJ3HzoaCfQ7eGYxSZJOuvMbWMknhsMjXyk41Dzx47ey9Hwqgy+xHWQHGtszov1OI/IekuMg1rxDaAspT0IxDecVw3+ipc=
        script: |
          # Crear el directorio .ssh si no existe
          mkdir -p ~/.ssh
          # Añadir la clave pública de GitHub a known_hosts del servidor
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          # Navega a la carpeta del proyecto en tu servidor
          cd public_html/public_html/chess_trainer
          # Descartar cambios locales y sincronizar con el remoto (soluciona ramas divergentes)
          git reset --hard origin/main
          # Ejecuta git pull para descargar los últimos cambios
          git pull
          # (Opcional) Aquí podrías añadir más comandos, como limpiar la caché
          echo "Despliegue completado exitosamente!"